Create interfaces to make EntryLookup and ManifestLookup are interchangable
symfony/webpack-encore-bundle pull request #6
Opened 2018-10-25 03:56 UTC by codayblue

This will fix issue #2 

This is a very simple change to create a set of interfaces to make parts of the bundle changeable by the user. With this change it makes the bundle more flexible because people can other developers can change the functionality to match what they need.

2018-10-26 15:21 UTC, weaverryan reviewed
Hey Cody!

I just "hjacked" this PR a little bit - I think we should make a few tweaks to the interfaces themselves so that they're more solid and specific (this was actually my mistake - but when you created the interfaces, it was more obvious).

Also, we can do it in another PR, but we (at some point) will need to create some new bundle configuration so that the user can specify an alternate service to be used for the entrypoint lookup and manifest lookup.

Thanks!

2018-10-26 15:21 UTC, weaverryan commented on src/Asset/EntrypointLookupInterface.php
> +namespace Symfony\WebpackEncoreBundle\Asset;
Missing license header. Rebase to the current master and run `php vendor/bin/php-cs-fixer fix` and it'll just handle all of this automatically

2018-10-26 15:21 UTC, weaverryan commented on src/Asset/EntrypointLookupInterface.php
> +    public function reset();
TODO for later - when Symfony 4.2 is released, we can make this interface extend https://github.com/symfony/contracts/blob/master/Service/ResetInterface.php

2018-10-26 15:21 UTC, weaverryan commented on src/Asset/EntrypointLookupInterface.php
> +    public function getJavaScriptFiles(string $entryName): array;
Now that I see this interface, I think we should "clean it up" a little bit. I think we should create a new exception class - e.g. `EntrypointNotFoundException` and advertise above this method in phpdoc that this exception should be thrown if the entry does not exist.

2018-10-26 15:21 UTC, weaverryan commented on src/Asset/ManifestLookupInterface.php
> +    public function getManifestPath(string $path): ?string;
Same as the EntrypointLookupInterface: let's make this return `string` (not `?string`) and create a new `ManifestKeyNotFoundException` that we should throw if the key does not exist (and rename `$path` to `$key`).

2018-10-27 07:59 UTC, codayblue commented
I made the changes requested. I assumed that the exceptions should be implemented. So I tried implementing the way I thought they were meant to be.

2018-10-30 15:06 UTC, codayblue commented
@weaverryan is there anything else needed for this PR?

2018-11-02 14:00 UTC, weaverryan requested changes
Ok, one more round of changes! I've caused you some conflicts as you expected (sorry!) and I've deleted the ManifestLookup system entirely, so that will simplify!

Thanks!

2018-11-02 14:00 UTC, weaverryan commented on src/Asset/EntrypointLookup.php
> +            throw new EntrypointNotFoundException();
I think this needs to be moved down to replace the 2 `InvalidArgumentException` in `validateEntryName`. It's actually ok if `$this->getEntryFiles()` returns an empty array: that's possible if you pass a *valid* entry name, but there are no js for it, for example.

This will also make `getCssFiles()` instantly throw this new exception under the same conditions.

2018-11-02 14:00 UTC, weaverryan commented on src/Asset/EntrypointLookupInterface.php
> +     * @throws EntrypointNotFoundException for if a entry name is passed in and no results were found
`@throws EntrypointNotFoundException if an entry name is passed that does not exist in entrypoints.json`

2018-11-02 14:00 UTC, weaverryan commented on src/Asset/EntrypointLookupInterface.php
> +    public function getCssFiles(string $entryName): array;
Same `@throws` above this

2018-11-02 14:00 UTC, weaverryan commented on src/Asset/EntrypointLookupInterface.php
> +     * @return array
No need for the `@param` or `@return` as they are specified via the type-hints / return type

2018-11-02 14:00 UTC, weaverryan commented on src/Asset/EntrypointLookupInterface.php
> +     * @return array
No need for the `@param` or `@return` as they are specified via the type-hints / return type

2018-11-02 14:00 UTC, weaverryan commented on src/Asset/ManifestLookup.php
> +class ManifestLookup implements ManifestLookupInterface
Sorry - I killed this class entirely

2018-11-02 14:00 UTC, weaverryan commented on src/Asset/EntrypointLookupInterface.php
> +     * TODO for later - when Symfony 4.2 is released, use https://github.com/symfony/contracts/blob/master/Service/ResetInterface.php instead.
Don't include this TODO here. Sorry, I realized I confused you on this part! I was just dropping a note in the PR - but we usually don't add things like this in the code.

2018-11-03 14:49 UTC, codayblue commented
@weaverryan I have made the requested changes and resolved the conflicts

2018-11-03 18:31 UTC, weaverryan approved these changes

2018-11-03 19:32 UTC, weaverryan commented
Thank you Cody!

2018-11-03 19:32 UTC, merged