Reset default EntrypointLookup on exception to fix #21 and #73
symfony/webpack-encore-bundle pull request #74
Opened 2019-08-06 09:20 UTC by tbmatuka

Since @ckrack seems to be unavailable to continue working on #21, I figured this would be faster :)

I don't like having `_default` hardcoded in the listener, but I see no other options right now.
I thought about adding a `resetAll()` method to EntrypointLookupCollection, but there were a couple of issues with that:
1. It would either be a BC break if I added it to the interface, or an important method that isn't interfaced and I don't really like either of those.
2. I couldn't even implement it because the container that we get in the collection only has `has()` and `get()` methods, so I couldn't go through it. This would also have to be replaced (and break BC) to implement `resetAll()`.

Fixes https://github.com/symfony/demo/issues/910

2019-08-08 21:42 UTC, Lyrkan commented
> I don't like having _default hardcoded in the listener, but I see no other options right now.
> I thought about adding a resetAll() method to EntrypointLookupCollection, but there were a couple of issues with that

Wouldn't it be possible to handle that using the `WebpackEncoreExtension` (even though I agree that having a `all()` and/or a `resetAll()` in the `EntrypointLookupCollection` would have been a better solution)?

1) add a `$builds` argument to the constructor of `webpack_encore.exception_listener`
2) use `$container->getDefinition('webpack_encore.exception_listener')->replaceArgument(...)` to inject the list of available builds in it

2019-08-08 23:39 UTC, tbmatuka commented
I made it work like you suggested. I still don't love it, but I like it a lot better than before.

2019-08-09 12:58 UTC, weaverryan requested changes
Minor comments - thanks for moving this forward!

2019-08-09 12:58 UTC, weaverryan commented on src/EventListener/ExceptionListener.php
> +    private $entrypointNames;
I believe these are `buildNames` - we should change `entrypoint` -> `build` everywhere in this class

2019-08-09 12:58 UTC, weaverryan commented on src/EventListener/ExceptionListener.php
> +namespace Symfony\WebpackEncoreBundle\EventListener;
can you add LICENSE header at the top?

2019-08-09 12:58 UTC, weaverryan commented on src/EventListener/ExceptionListener.php
> +}
Could we add a very basic unit test for this class? There isn't much to test, but having at least ONE basic test will protect us from making any super silly typos now or in the future.

2019-08-09 12:58 UTC, weaverryan commented on src/Resources/config/services.xml
> +            <argument /> <!-- build list of entrypoint paths -->
```suggestion
            <argument /> <!--collection of build names -->
```

2019-08-09 14:59 UTC, tbmatuka commented
@weaverryan should be all done, can you take a look?

2019-08-28 14:35 UTC, tbmatuka commented
@weaverryan can you please take a look?

2019-09-11 16:25 UTC, tbmatuka commented
@weaverryan it's been a month now, can you please take a quick look so that we can move this along?

2019-11-05 10:23 UTC, tbmatuka commented
@weaverryan @Lyrkan this has been waiting for review/merge almost three months now, can we please move it along?

2020-01-31 15:32 UTC, weaverryan commented
Sorry for the long delay @tbmatuka - but thank you SO much for finishing this :). Cheers!

2020-01-31 15:32 UTC, merged